## Data Science with Python POA

In [1]:
import math


In [4]:
math.sqrt(25)

5.0

In [6]:
math.pi

3.141592653589793

In [7]:
import math as mt
mt.sqrt(25)

5.0

#### Import Modules

In [9]:
import numpy

In [10]:
import math

In [11]:
from scipy import stats


#### Work with Arrays (numpy)

In [12]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [14]:
a.ndim

2

In [15]:
a.dtype.name

'int32'

In [16]:
a.dtype

dtype('int32')

In [17]:
a.itemsize

4

In [18]:
a.size


15

In [19]:
type(a)


numpy.ndarray

In [20]:
b = np.array([6,7,8])
b


array([6, 7, 8])

#### Arguments in parenthesis (otherwise would produce error)

In [21]:
type b


SyntaxError: invalid syntax (<ipython-input-21-4e69ad99bd20>, line 1)

In [45]:
type(b)

numpy.ndarray

In [23]:
print(b)

[6 7 8]


In [24]:
from numpy import random

In [25]:
import numpy as np


In [36]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
dataOne

array([[0.2452438 , 0.79840394, 0.76259657, 0.75348343, 0.03265049],
       [0.38133974, 0.58919331, 0.34751307, 0.40842375, 0.71301128],
       [0.23130216, 0.7580732 , 0.34776149, 0.14485531, 0.45771265],
       [0.22331343, 0.47333309, 0.11028767, 0.13498614, 0.84737341],
       [0.29448542, 0.2676234 , 0.10932002, 0.94255595, 0.62781271]])

In [37]:
dataOne

array([[0.2452438 , 0.79840394, 0.76259657, 0.75348343, 0.03265049],
       [0.38133974, 0.58919331, 0.34751307, 0.40842375, 0.71301128],
       [0.23130216, 0.7580732 , 0.34776149, 0.14485531, 0.45771265],
       [0.22331343, 0.47333309, 0.11028767, 0.13498614, 0.84737341],
       [0.29448542, 0.2676234 , 0.10932002, 0.94255595, 0.62781271]])

#### Numpy functions

In [38]:
np.mean(dataOne)

0.4401062178612265

In [39]:
np.median(dataOne)

0.38133973557551426

In [40]:
np.max(dataOne)

0.9425559534395582

In [41]:
np.min(dataOne)

0.032650485249654526

#### "isnan" does not validate for Null values

In [42]:
mt.isnan(dataOne)

TypeError: only size-1 arrays can be converted to Python scalars

In [43]:
mt.isnan(b)

TypeError: only size-1 arrays can be converted to Python scalars

#### "None" is the keyword for Null in Python

In [46]:
dataOne is None 

False

In [48]:
b is None

False

#### Arrays are 0 (zero) based

In [50]:
b

array([6, 7, 8])

In [51]:
mt.isnan(b[0])

False

In [52]:
mt.isnan(b[3])

IndexError: index 3 is out of bounds for axis 0 with size 3

#### Funcions or constants need to be preceeded by their Module in the format module.function

In [53]:
factorial(3)

NameError: name 'factorial' is not defined

In [54]:
mt.factorial(3)

6

In [55]:
mt.factorial(b[0])

720

In [56]:
pi

NameError: name 'pi' is not defined

In [57]:
mt.pi

3.141592653589793

In [58]:
mt.e

2.718281828459045

#### Stats functions (from scipy module)

In [59]:
stats.rv_histogram(histogram,b)

NameError: name 'histogram' is not defined

In [60]:
hist = np.histogram(b)

In [61]:
hist_dist = stats.rv_histogram(hist)

In [62]:
hist_dist

In [63]:
stats.describe(b)

DescribeResult(nobs=3, minmax=(6, 8), mean=7.0, variance=1.0, skewness=0.0, kurtosis=-1.5)

In [64]:
stats.describe(a)

DescribeResult(nobs=3, minmax=(array([0, 1, 2, 3, 4]), array([10, 11, 12, 13, 14])), mean=array([5., 6., 7., 8., 9.]), variance=array([25., 25., 25., 25., 25.]), skewness=array([0., 0., 0., 0., 0.]), kurtosis=array([-1.5, -1.5, -1.5, -1.5, -1.5]))

In [65]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
b


array([6, 7, 8])

In [67]:
stats.describe(b)

DescribeResult(nobs=3, minmax=(6, 8), mean=7.0, variance=1.0, skewness=0.0, kurtosis=-1.5)

In [68]:
stats.gmean(b)

6.9520532897729

In [70]:
stats.tmax(b)

8

In [71]:
stats.tmin(b)

6

#### When applying functions to arrays, need to be same shape

In [72]:
stats.tmax(a,b)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [73]:
stats.tmax(b,b)

8

In [74]:
c = np.array([1,2,3])
c


array([1, 2, 3])

In [76]:
stats.tmax(c)

3

In [77]:
stats.tmean(b)

7.0

In [79]:
stats.tvar(b)

1.0

In [80]:
stats.find_repeats(b)

RepeatedResults(values=array([], dtype=float64), counts=array([], dtype=int64))

In [81]:
stats.rankdata(b)

array([1., 2., 3.])

In [82]:
stats.ranksums(b,c)

RanksumsResult(statistic=1.9639610121239315, pvalue=0.049534613435626706)

#### Array must have the same number of dimensions

In [85]:
stats.ranksums(a,b)

ValueError: all the input arrays must have same number of dimensions

In [86]:
stats.ranksums(b,b)

RanksumsResult(statistic=0.0, pvalue=1.0)

#### Functions

In [87]:
print('Data Science')

Data Science


In [88]:
print(b)

[6 7 8]


 #### Variables:
 Normal variable names must start with a letter

In [90]:
variableName1 = 'Data Science' + " 2020"

In [ ]:
Variables names are case sensitive

In [91]:
print(variablename1)

NameError: name 'variablename1' is not defined

In [93]:
print(variableName1)

Data Science 2020


In [94]:
variableName=25
type(variableName)

int

In [95]:
variableName2=3.5
type(variableName2)

float

In [96]:
variableName3='Data Science'
type(variableName3)

str

In [97]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


#### Operations with Variables
Variables need to have same type in Operations otherwise use "Type casting"

https://www.programiz.com/python-programming/type-conversion-and-casting

In [99]:
varFour = 25
varFive = 'Data Science'
varSix = varFour + varFive
print(varSix)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [101]:
varFour_str = str(varFour)
varSix = varFour_str + " " + varFive
print(varSix)

25 Data Science


#### Lists and Dictionaries

In [107]:
#  elements starting at index 1 to the 3rd element
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [108]:
student = {'John': 70, 'Lisa': 90, 'Peter': 86, 'Chris': 95, 'Mary': 65}
student


{'John': 70, 'Lisa': 90, 'Peter': 86, 'Chris': 95, 'Mary': 65}

In [110]:
student['Lisa']

90

In [111]:
# Defining variables
J = student['John']
L = student['Lisa']
P = student['Peter']
C = student['Chris']
M = student['Mary']
print(J, L, P, C, M)

70 90 86 95 65


In [112]:
# Checking for Null values
student is None

False

In [122]:
import math as mt


In [123]:
mt.ceil(L)

90

In [124]:
mt.factorial(M)

8247650592082470666723170306785496252186258551345437492922123134388955774976000000000000000

In [127]:
mt.gcd(L,P)

2

In [128]:
mt.remainder(P,M)

21.0

In [131]:
mt.pow(L,M)

1.0611166119964725e+127

## Comments

Although there are different components in the installation of Python and other modules for this task, the process was straightforward. In some instances there was a need to research about "PATH"s and Directories on where to install and how to invoke the components.


The tutorial was very helful since it delineates the process to install and get familiar with the tools needed for this task. The recommendation to others is to allow enough time to go over tutorials and get familiar with all the tools to take advantage of their functionality.

Valuable lesson obtained from this task is the possibility to learn a Data Science platform (Anaconda) along with a Software Development platform (GitHub), and how they interact with programming languages. The possibility to learn Jupyter Notebook to create documents containing code, visualizations and text was also a great lesson learned.